# Generated by Django 3.2.6 on 2021-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='issues', to='main.IssueLabel'),
        ),
    ]
