# Generated by Django 3.2.4 on 2021-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210806_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuelabel',
            name='color',
            field=models.CharField(default='#a00000', max_length=7),
            preserve_default=False,
        ),
    ]
