# Generated by Django 3.2.4 on 2021-08-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_issuelabel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects_moderating',
            field=models.ManyToManyField(related_name='moderators', to='main.Project'),
        ),
    ]
