# Generated by Django 3.2.6 on 2021-08-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_issue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='guest_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
