# Generated by Django 3.2.6 on 2021-08-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210811_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='guest_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
