# Generated by Django 3.2.6 on 2021-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210811_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='publicity',
            field=models.IntegerField(choices=[('private', 0), ('public', 1)], default=0),
        ),
    ]
