# Generated by Django 3.2.6 on 2021-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_issue_publicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='publicity',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'public')], default=0),
        ),
    ]
