# Generated by Django 3.2.6 on 2021-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_issue_publicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_status_change',
            field=models.BooleanField(default=False),
        ),
    ]
